# Generated by Django 4.0.6 on 2022-07-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionTags',
            new_name='TransactionTag',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
