# Generated by Django 4.0.4 on 2022-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
