# Generated by Django 4.0.4 on 2022-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
